### ISSUE TITLE
Replace varchar with TEXT?

### ISSUE THREAD

**Issue by lascellesabercrombie** [fac24/week3-Asmahan-Hussain-Maria-Petra#29]
https://github.com/fac24/week3-Asmahan-Hussain-Maria-Petra/blob/3ffec628a741b3b33260875221cf73976a09f96a/database/init.sql#L7

On our last project, Oli was able to break our app by entering a username longer than 20 characters. I don't think you limit the character length on the user end, so it might be simplest just to change the VARCHAR(20) with TEXT and let people enter usernames as long as they like them to be.

**Comment by mariaalouisaa** [comment]
Thanks for the reminder!! 🙂
